---
name: Ali and Seth
description: Ali and Seth
logo: assets/images/kiss-backlit.jpg
favicon: assets/images/favicon.ico
email: info@sethandali.com
mailchimp-list: 
include:
- _pages
- admin
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  seth:
    name: Seth
    site: ''
    avatar: "/assets/images/seth-avatar.jpg"
    bio: Seth Bio
    email: ''
    twitter: ''
  ali:
    name: Ali
    site: ''
    avatar: "/assets/images/ali-avatar.jpg"
    bio: Ali bio
    email: ''
    twitter: ''
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: ali
    avatar: "/assets/images/kiss-backlit.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
