---
name: SethAndAli.com
description: Cool stuff
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: info@sethandali.com
mailchimp-list: 
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  seth:
    name: Seth
    site: ''
    avatar: ''
    bio: ''
    email: ''
    twitter: ''
  ali:
    name: Ali
    site: ''
    avatar: ''
    bio: ''
    email: ''
    twitter: ''
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: ali
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
